#!/bin/bash
# Author: Iain Douglas <centos@1n6.org.uk>
# Author: Rene Diepstraten <rene@renediepstraten.nl>
#
# Check the binaries from the package exist and run ok

function ExitFail {
    t_Log "Fail"
    exit $FAIL
}

[[ $centos_ver =~ ^6|7$ ]] || exit
t_Log "Checking binaries are present and run on C7"

[ "$(readlink -e /usr/bin/gunzip)" == "/usr/bin/gunzip" ] || ExitFail
[ "$(readlink -e /usr/bin/gzip)" == "/usr/bin/gzip" ] || ExitFail

for binary in gunzip gzip zcat gzexe zcmp zdiff zegrep zfgrep zforce zgrep zless zmore znew
do
    echo -n "$binary "
    $binary --version &>/dev/null || ExitFail
done
echo ""
t_Log "PASS"
