#!/bin/bash
# Author: Iain Douglas <centos@1n6.org.uk>
echo "Running $0"
echo "Testing sg"
sg testshadow "touch /var/tmp/sg"
t_CheckExitStatus $?
echo "Check sg worked"
ls -l /var/tmp/sg | grep -q testshadow
t_CheckExitStatus $?
rm /var/tmp/sg
